[package]
name = "interpreter_js"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
thiserror = "1"

sf_std = { path = "../host_to_core_std", package = "host_to_core_std" }
map_std = { path = "../core_to_map_std", package = "core_to_map_std" }

quickjs-wasm-rs = { version = "0.1", features = [] }

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1"}

serde_urlencoded = { version = "0.7" }
base64 = { version = "0.21" }

slab = "0.4"
