[package]
name = "interpreter_js"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
thiserror = { workspace = true }

sf_std = { path = "../host_to_core_std", package = "host_to_core_std" }
map_std = { path = "../core_to_map_std", package = "core_to_map_std" }

quickjs-wasm-rs = { git = "https://github.com/Shopify/javy.git", tag = "v0.6.0", features = [] }
# quickjs-wasm-sys = { git = "https://github.com/Shopify/javy.git", tag = "v0.6.0", features = [] }

serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
base64 = { workspace = true }

tracing = { workspace = true }

[dev-dependencies]
sf_std = { path = "../host_to_core_std", package = "host_to_core_std", features = ["stub_ffi"] }
