name = "example"
main = "src/index.ts"
compatibility_date = "2023-04-18"

workers_dev = true

rules = [
  # TODO: figure out the glob from superface folder only - not working for some reason
  { type = "Data", globs = ["**/*.map.js", "**/*.profile", "**/*.provider.json"], fallthrough = true }
]
