[package]
name = "host_to_core_std"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1"

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_urlencoded = { version = "0.7" }
