[package]
name = "comlink_language"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = { workspace = true }
serde_json = { workspace = true }

either = { version = "1.8" }

rowan = { version = "0.15" }
