---
type: object
patternProperties:
  "^[a-z][_\\-a-z]*$":
    type: object
    oneOf:
    - type: object
      properties:
        username:
          type: string
        password:
          type: string
      additionalProperties: false
    - type: object
      properties:
        token:
          type: string
      additionalProperties: false
    - type: object
      properties:
        apikey:
          type: string
      additionalProperties: false