name: Release package
on:
  workflow_dispatch:
    inputs:
      release-level:
        description: "Release level"
        required: true
        type: choice
        default: prerelease
        options:
        - prerelease
        - patch
        - minor
        - major
      release-kind:
        description: "Release kind"
        required: false
        type: choice
        default: alpha
        options:
        - alpha
        - beta
        - rc
        - stable

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "18"
          cache: yarn
          cache-dependency-path: integration/yarn.lock
      - name: Cache cargo registry and build directory
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            core/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache WASI SDK
        uses: actions/cache@v3
        with:
          path: core/wasi-sdk-*
          key: wasisdk-${{ runner.os }}-${{ runner.arch }}
      - name: Install wasm-opt
        run: |
          sudo apt-get update
          sudo apt-get install binaryen
      - name: Install rust target
        run: rustup target add wasm32-wasi
      # build and store
      - name: Run make to build core
        env:
          CARGO_INCREMENTAL: "0" # disable incremental to reduce load on the cache
        run: make build_core MODE=release OS=${{ runner.os }}
      - name: Upload artifact core-async.wasm
        uses: actions/upload-artifact@v3
        with:
          name: core-async-wasm
          path: core/dist/core-async.wasm
      - name: Upload artifact core.wasm
        uses: actions/upload-artifact@v3
        with:
          name: core-wasm
          path: core/dist/core.wasm
      # resolve release version
      - name: Resolve release level
        id: release-level
        run: scripts/release-level.sh ${{ inputs.release-level }} ${{ inputs.release-kind }} >>$GITHUB_OUTPUT
      - name: Resolve release version
        id: release-version
        run: scripts/release-version.sh ./VERSION ${{ steps.release-level.outputs.RELEASE_LEVEL }} ${{ steps.release-level.outputs.RELEASE_PREID }} >>$GITHUB_OUTPUT
    outputs:
      RELEASE_LEVEL: ${{ steps.release-level.outputs.RELEASE_LEVEL }}
      RELEASE_PREID: ${{ steps.release-level.outputs.RELEASE_PREID }}
      RELEASE_TAG: ${{ steps.release-level.outputs.RELEASE_TAG }}
      RELEASE_VERSION: ${{ steps.release-version.outputs.RELEASE_VERSION }}

  host-js:
    needs: [core]
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Git configuration
      run: |
        git config --global user.email "bot@superface.ai"
        git config --global user.name "GitHub Actions release workflow"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
        node-version: "18"
        cache: yarn
        cache-dependency-path: host/js/yarn.lock
    - uses: actions/download-artifact@v3
      with:
        name: core-async-wasm
        path: host/js/assets
    # build
    - name: Build host/js
      working-directory: host/js
      run: |
        yarn install --frozen-lockfile
        yarn build
    # publish and push git
    - name: Publish
      working-directory: host/js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_BOT_PAT }}
      run: yarn publish --verbose --no-git-tag-version --access public --new-version ${{ needs.core.outputs.RELEASE_VERSION }} --tag ${{ needs.core.outputs.RELEASE_TAG }}
    - name: Commit package.json changes
      working-directory: host/js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add package.json
        git commit -m "chore: release host/js ${{ needs.core.outputs.RELEASE_VERSION }}"
        git push origin

  # TODO: additional hosts

  github-release:
    needs: [core, host-js]
    runs-on: ubuntu-latest
    steps:
    - name: Update changelog (if stable)
      uses: superfaceai/release-changelog-action@v1
      if: needs.core.outputs.RELEASE_TAG == 'latest'
      with:
        path-to-changelog: CHANGELOG.md
        version: ${{ needs.core.outputs.RELEASE_VERSION }}
        operation: release
    - name: Commit CHANGELOG.md, VERSION and create git tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        printf "${{ needs.core.outputs.RELEASE_VERSION }}" >VERSION
        git add CHANGELOG.md VERSION
        git commit -m "chore: release one-sdk ${{ needs.core.outputs.RELEASE_VERSION }}"
        git tag "v${{ needs.core.outputs.RELEASE_VERSION }}"
        git push origin && git push --tags
    # update GitHub release with changelog
    - name: Get release version changelog
      id: get-changelog
      if: needs.core.outputs.RELEASE_TAG == 'latest'
      uses: superfaceai/release-changelog-action@v1
      with:
        path-to-changelog: CHANGELOG.md
        version: ${{ needs.core.outputs.RELEASE_VERSION }}
        operation: read
    - name: Update GitHub release documentation
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ needs.core.outputs.RELEASE_VERSION }}"
        body: ${{ steps.get-changelog.outputs.changelog }}
        prerelease: ${{ needs.core.outputs.RELEASE_TAG != 'latest' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
