name: Release package
on:
  workflow_dispatch:
    inputs:
      release-level:
        description: "Release level"
        required: true
        type: choice
        default: prerelease
        options:
        - prerelease
        - patch
        - minor
        - major
      release-kind:
        description: "Release kind"
        required: false
        type: choice
        default: alpha
        options:
        - alpha
        - beta
        - rc
        - stable

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "18"
          cache: yarn
          cache-dependency-path: integration/yarn.lock
      - name: Cache cargo registry and build directory
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            core/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Cache WASI SDK
        uses: actions/cache@v3
        with:
          path: core/wasi-sdk-*
          key: wasisdk-${{ runner.os }}-${{ runner.arch }}
      - name: Install wasm-opt
        run: |
          sudo apt-get update
          sudo apt-get install binaryen
      - name: Install rust target
        run: rustup target add wasm32-wasi
      # build and store
      - name: Run make to build core
        env:
          CARGO_INCREMENTAL: "0" # disable incremental to reduce load on the cache
        run: make build_core MODE=release OS=${{ runner.os }}
      - name: Upload artifact core-async.wasm
        uses: actions/upload-artifact@v3
        with:
          name: core-async-wasm
          path: core/dist/core-async.wasm
      - name: Upload artifact core.wasm
        uses: actions/upload-artifact@v3
        with:
          name: core-wasm
          path: core/dist/core.wasm
  
  # TODO: create github release?

  host-js:
    needs: core
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Git configuration
      run: |
        git config --global user.email "bot@superface.ai"
        git config --global user.name "GitHub Actions release workflow"
    - uses: actions/checkout@v3
    - name: Release level processing
      run: scripts/release-level.sh ${{ inputs.release-level }} ${{ inputs.release-kind }} >>$GITHUB_ENV

    - uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
        node-version: "18"
        cache: yarn
        cache-dependency-path: host/js/yarn.lock
    - uses: actions/download-artifact@v3
      with:
        name: core-async-wasm
        path: host/js/assets
    # build
    - name: Install dependencies
      working-directory: host/js
      run: yarn install --frozen-lockfile
    - name: Build host
      working-directory: host/js
      run: yarn build
    # version and (TODO) changelog
    - name: Bump release version
      working-directory: host/js
      run: echo "NEW_VERSION=$(npm --no-git-tag-version --preid $RELEASE_PREID version $RELEASE_LEVEL)" >>$GITHUB_ENV
    - name: Commit CHANGELOG.md and package.json changes and create tag
      working-directory: host/js
      run: |
        git add package.json
        git commit -m "chore: release host/js $NEW_VERSION"
        git tag $NEW_VERSION
    # publish and push git
    - name: Publish
      working-directory: host/js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_BOT_PAT }}
      run: yarn publish --verbose --access public --new-version $NEW_VERSION --tag $RELEASE_TAG
    - name: Push changes to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin && git push --tags

  # TODO: additional hosts
